nozama/config/routes.rb
Nozama::Application.routes.draw do

  match '/indexbatchinventory', to: 'inventories#batch_index', via: 'get'
  match '/batchinventory', to: 'inventories#batch_inventory', via: 'get'
  match '/batchinventorydeleteone', to: 'inventories#batch_delete', via: 'get'
  match '/batchinventorydeleteall', to: 'inventories#batch_delete_all', via: 'get'
  match '/batchinventoryshow', to: 'inventories#show', via: 'get'
  match '/inventorysearch', to: 'inventories#search', via: 'get'
  match '/inventorysearchindex', to: 'inventories#search_index', via: 'get'

  match '/indexbatchsales', to: 'sales#batch_index', via: 'get'
  match '/batchsales', to: 'sales#batch_sales', via: 'get'
  match '/batchsalesdeleteone', to: 'sales#batch_delete', via: 'get'
  match '/batchsalesdeleteall', to: 'sales#batch_delete_all', via: 'get'
  match '/salessearch', to: 'sales#search', via: 'get'
  match '/salessearchindex', to: 'sales#search_index', via: 'get'
  match '/salesstatistics', to: 'sales#statistics', via: 'get'

  resources :users
  resources :inventories
  resources :sales
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'

end

nozama/app/views/layouts/_footer.html.erb
<footer class="footer">
    <nav>
        <ul>
        </ul>
    </nav>
</footer>

nozama/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
        <div class="container">
            <%= link_to 'Nozama', root_path, id: 'logo' %>
            <nav>
                <ul class="nav pull-right">
                    <!--<li><%= link_to 'Home', root_path %></li>-->
                    <% if signed_in? %>
                        <li id="fat-menu" class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Inventory <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><%= link_to 'List Inventory', inventories_path %></li>
                                <li><%= link_to 'List Uploads', indexbatchinventory_path %></li>
                                <li><%= link_to 'Search Inventory', inventorysearch_path %></li>
                                <li class="divider"></li>
                                <li><%= link_to 'Upload Inventory', new_inventory_path %></li>
                            </ul>
                        </li>
                        <li id="fat-menu" class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Sales <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><%= link_to 'List Sales', sales_path %></li>
                                <li><%= link_to 'List Uploads', indexbatchsales_path %></li>
                                <li><%= link_to 'Search Sales', salessearch_path %></li>
                                <li><%= link_to 'Statistics', salesstatistics_path %></li>
                                <li class="divider"></li>
                                <li><%= link_to 'Upload Sales', new_sale_path %></li>
                            </ul>
                        </li>
                        <li id="fat-menu" class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Account <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><%= link_to 'Profile', current_user %></li>
                                <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
                                <li class="divider"></li>
                                <li>
                                    <%= link_to 'Sign Out', signout_path, method: 'delete' %>
                                </li>
                            </ul>
                        </li>
                    <% else %>
                        <li><%= link_to 'Sign In', signin_path %></li>
                    <% end %>
                </ul>
            </nav>
        </div>
    </div>
</header>

nozama/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

nozama/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <!--<%= debug(params) if Rails.env.development? %>-->
</div>
</body>
</html>