nozama/config/routes.rb
Nozama::Application.routes.draw do

  match '/indexbatchinventory', to: 'inventories#batch_index', via: 'get'
  match '/batchinventory', to: 'inventories#batch_inventory', via: 'get'
  match '/batchinventorydeleteone', to: 'inventories#batch_delete', via: 'get'
  match '/batchinventorydeleteall', to: 'inventories#batch_delete_all', via: 'get'
  match '/batchinventoryshow', to: 'inventories#show', via: 'get'
  match '/inventorysearch', to: 'inventories#search', via: 'get'
  match '/inventorysearchindex', to: 'inventories#search_index', via: 'get'

  match '/indexbatchsales', to: 'sales#batch_index', via: 'get'
  match '/batchsales', to: 'sales#batch_sales', via: 'get'
  match '/batchsalesdeleteone', to: 'sales#batch_delete', via: 'get'
  match '/batchsalesdeleteall', to: 'sales#batch_delete_all', via: 'get'
  match '/salessearch', to: 'sales#search', via: 'get'
  match '/salessearchindex', to: 'sales#search_index', via: 'get'
  match '/salesstatistics', to: 'sales#statistics', via: 'get'

  resources :users
  resources :inventories
  resources :sales
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'

end

nozama/app/models/user.rb
class User < ActiveRecord::Base
  has_many :sales, dependent: :destroy, order: 'shipment_date asc'
  has_many :inventories, dependent: :destroy, order: 'received_date asc'
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

nozama/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = 'Welcome to Nozama!'
      redirect_to @user
    else
      render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile Updated.'
      redirect_to @user
    else
      render 'edit'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'User Deleted.'
    redirect_to users_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

nozama/app/helpers/users_helper.rb
module UsersHelper
end

nozama/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, 'error') %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

nozama/app/views/users/_user.html.erb
<li>
    <%= link_to user.name, user %>
    <% if current_user.admin? && !current_user?(user) %>
        | <%= link_to 'delete', user, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
</li>

nozama/app/views/users/edit.html.erb
<% provide(:title, 'Edit User') %>
<h1>Update Your Profile</h1>

<div class="row">
    <div class="span6 offset3">
        <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages' %>

            <%= f.label :name %>
            <%= f.text_field :name %>

            <%= f.label :email %>
            <%= f.text_field :email %>

            <%= f.label :password %>
            <%= f.password_field :password %>

            <%= f.label :password_confirmation, 'Confirm Password' %>
            <%= f.password_field :password_confirmation %>

            <%= f.submit 'Save Changes', class: 'btn btn-large btn-primary' %>
        <% end %>
    </div>
</div>

nozama/app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1>All Users</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @users %>
</ul>

<%= will_paginate %>

nozama/app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign Up</h1>

<div class="row">
    <div class="span6 offset3">
        <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages' %>

            <%= f.label :name %>
            <%= f.text_field :name %>

            <%= f.label :email %>
            <%= f.text_field :email %>

            <%= f.label :password %>
            <%= f.password_field :password %>

            <%= f.label :password_confirmation, 'Confirm Password' %>
            <%= f.password_field :password_confirmation %>

            <%= f.submit 'Create My Account', class: 'btn btn-large btn-primary' %>
        <% end %>
    </div>
</div>

nozama/app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
    <aside class="span4">
        <section>
            <h1>
                <%= @user.name %>
            </h1>
        </section>
    </aside>
</div>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>