nozama/config/routes.rb
Nozama::Application.routes.draw do

  match '/indexbatchinventory', to: 'inventories#batch_index', via: 'get'
  match '/batchinventory', to: 'inventories#batch_inventory', via: 'get'
  match '/batchinventorydeleteone', to: 'inventories#batch_delete', via: 'get'
  match '/batchinventorydeleteall', to: 'inventories#batch_delete_all', via: 'get'
  match '/batchinventoryshow', to: 'inventories#show', via: 'get'
  match '/inventorysearch', to: 'inventories#search', via: 'get'
  match '/inventorysearchindex', to: 'inventories#search_index', via: 'get'

  match '/indexbatchsales', to: 'sales#batch_index', via: 'get'
  match '/batchsales', to: 'sales#batch_sales', via: 'get'
  match '/batchsalesdeleteone', to: 'sales#batch_delete', via: 'get'
  match '/batchsalesdeleteall', to: 'sales#batch_delete_all', via: 'get'
  match '/salessearch', to: 'sales#search', via: 'get'
  match '/salessearchindex', to: 'sales#search_index', via: 'get'
  match '/salesstatistics', to: 'sales#statistics', via: 'get'

  resources :users
  resources :inventories
  resources :sales
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'

end

nozama/app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true

  def self.total_for(date)
    where('date(shipment_date) = ?', date).sum(:item_price_per_unit)
  end

  def self.totalcount_for(date)
    where('date(shipment_date) = ?', date).count()
  end

end

nozama/app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :signed_in_user, only: [:index, :create, :edit, :update, :destroy]
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    if params[:fnsku] && params[:item_id]
      @sales = current_user.sales.where(:user_id => current_user.id, :fnsku => params[:fnsku], :item_id => params[:item_id]).group(:amazon_order_id).paginate(page: params[:page])
    else
      @sales = current_user.sales.where(:user_id => current_user.id).group(:fnsku, :item_id, :amazon_order_id).paginate(page: params[:page])
    end
  end

  def statistics
    @sales = current_user.sales.where(:user_id => current_user.id)
  end

  def batch_sales
    @sales = Sale.where(:user_id => current_user.id, :batch_id => params[:batch_id]).group(:fnsku, :item_id, :amazon_order_id).paginate(page: params[:page])
  end

  def batch_index
    @sales = Sale.where(:user_id => current_user.id).group(:batch_id).paginate(page: params[:page])
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    fnsku = @sale.fnsku
    item = @sale.item_id
    sale = @sale.amazon_order_id

    if params[:batch_id]
      @sale.quantity = current_user.sales.where(:user_id => current_user.id, :fnsku => fnsku, :item_id => item, :amazon_order_id => sale, :batch_id => params[:batch_id]).sum(:quantity)
    else
      @sale.quantity = current_user.sales.where(:user_id => current_user.id, :fnsku => fnsku, :item_id => item, :amazon_order_id => sale).sum(:quantity)
    end
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  def search
    @sale = Sale.new
  end

  def search_index
    if params[:amazon_order_id]
      @sales = current_user.sales.where(:user_id => current_user.id, :amazon_order_id => params[:amazon_order_id]).group(:fnsku, :item_id, :amazon_order_id).paginate(page: params[:page])
    elsif params[:fnsku]
      @sales = current_user.sales.where(:user_id => current_user.id, :fnsku => params[:fnsku]).group(:fnsku, :item_id, :amazon_order_id).paginate(page: params[:page])
    end
  end

  # POST /sales
  # POST /sales.json
  def create
    if params[:name] == 'Upload File'
      fileUpload = true
    elsif params[:name] == 'Search'
      searchQuery = true
    end

    if params[:sale] && params[:sale][:file]
      sale = Sale.where(:user_id => current_user.id).last

      if sale.nil?
        batchID = 1
      else
        batchID = sale.batch_id + 1
      end

      lines = params[:sale][:file].tempfile.readlines.map(&:chomp)
      validHeader = lines[0].split(/\t/)

      if validHeader[0] == 'shipment-date'
        lines.shift
        begin
          Sale.transaction do
            Inventory.transaction do
              lines.each do |line|
                parse = line.split(/\t/)
                quantities = parse[5].to_i
                for i in (1..quantities)
                  @inventory = Inventory.limit(1).order('received_date asc').where(:user_id => current_user.id, :fnsku => parse[2]).where('quantity_remaining > 0').first

                  if @inventory.nil?
                    daysInInventory = -1
                    itemID = -1
                  else
                    daysInInventory = (parse[0].to_datetime - @inventory.received_date).to_i
                    itemID = @inventory.id
                  end

                  @sale = current_user.sales.build(batch_id: batchID, item_id: itemID, days_in_inventory: daysInInventory, shipment_date: parse[0], sku: parse[1], fnsku: parse[2], asin: parse[3], fulfillment_center_id: parse[4], quantity: 1,
                                                   amazon_order_id: parse[6], currency: parse[7], item_price_per_unit: parse[8], shipping_price: parse[9], gift_wrap_price: parse[10],
                                                   ship_city: parse[11], ship_state: parse[12], ship_postal_code: parse[13])

                  if @inventory.nil?
                    @sale.save!
                  else
                    quantityRemaining = @inventory.quantity_remaining
                    @sale.save!
                    @inventory.update_attributes(:quantity_remaining => quantityRemaining - 1)
                  end
                end
              end
            end
          end
        rescue
          notice = 'Upload error.'
          redirect_to new_sale_path, :notice => notice
          return
        end
      else
        @sale = Sale.new
      end
    elsif params[:sale] && (params[:sale][:amazon_order_id] != '')
      redirect_to salessearchindex_path(:amazon_order_id => params[:sale][:amazon_order_id])
    elsif params[:sale] && (params[:sale][:fnsku] != '')
      redirect_to salessearchindex_path(:fnsku => params[:sale][:fnsku])
    else
      @sale = Sale.new
    end

    if fileUpload
      respond_to do |format|
        if @sale.save
          format.html { redirect_to sales_path, notice: 'Sales were successfully uploaded.' }
          format.json { render action: 'show', status: :created, location: @sale }
        else
          format.html { redirect_to new_sale_path, notice: 'Sales upload was unsuccessful.' }
          format.json { render json: @sale.errors, status: :unprocessable_entity }
        end
      end
    elsif searchQuery
      if params[:sale][:amazon_order_id] == '' && params[:sale][:fnsku] == ''
        respond_to do |format|
          format.html { redirect_to salessearch_path, notice: 'Enter Amazon Order ID or FNSKU to search.' }
          format.json { render json: @inventory.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def batch_delete
    Sale.delete(params[:id])
    respond_to do |format|
      format.html { redirect_to batchsales_path(:batch_id => params[:batch_id]), notice: 'Sale was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def batch_delete_all
    Sale.where(:batch_id => params[:batch_id], :user_id => current_user.id).delete_all
    respond_to do |format|
      format.html { redirect_to indexbatchsales_path, notice: 'Batch was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:user_id, :shipment_date, :sku, :fnsku, :asin, :fulfillment_center_id, :quantity, :amazon_order_id, :currency, :item_price_per_unit, :shipping_price,
      :gift_wrap_price, :ship_city, :ship_state, :ship_postal_code)
    end
end

nozama/app/helpers/sales_helper.rb
module SalesHelper
end

nozama/app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, 'error') %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

nozama/app/views/sales/batch_index.html.erb
<% provide(:title, 'Batch Sales Index') %>
<h1>Batch Sales Index</h1>
<div class='text-center'>
    <%= will_paginate %>
</div>
<table align="center">
    <thead>
    <tr>
        <th>Batch ID</th>
        <td>&nbsp&nbsp</td>
        <th>Uploaded</th>
        <td>&nbsp&nbsp</td>
        <th>Delete</th>
    </tr>
    </thead>

    <tbody>
    <% @sales.each do |sale| %>
        <tr>
            <td><%= link_to sale.batch_id, batchsales_path(:batch_id => sale.batch_id) %></td>
            <td>&nbsp&nbsp</td>
            <td><%= sale.created_at.strftime('%m/%d/%Y') %></td>
            <td>&nbsp&nbsp</td>
            <td><%= link_to 'Delete', batchsalesdeleteall_path(:batch_id => sale.batch_id), data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
</table>
<div class='text-center'>
    <%= will_paginate %>
</div>

nozama/app/views/sales/batch_sales.html.erb
<% provide(:title, 'Batch Sales') %>
<h1>Batch Sales</h1>
<div class='text-center'>
    <%= will_paginate %>
</div>
<table align="center">
    <thead>
    <tr>
        <th>Amazon Order ID</th>
        <td>&nbsp&nbsp</td>
        <th>FNSKU</th>
        <td>&nbsp&nbsp</td>
        <th>Shipment Date</th>
        <td>&nbsp&nbsp</td>
        <th>Delete</th>
    </tr>
    </thead>

    <tbody>
    <% @sales.each do |sale| %>
        <tr>
            <td><%= link_to sale.amazon_order_id, sale %></td>
            <td>&nbsp&nbsp</td>
            <td><%= sale.fnsku %></td>
            <td>&nbsp&nbsp</td>
            <td><%= sale.shipment_date.strftime('%m/%d/%Y') %></td>
            <td>&nbsp&nbsp</td>
            <td><%= link_to 'Delete', batchsalesdeleteone_path(:id => sale.id, :batch_id => sale.batch_id), data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
</table>
<div class='text-center'>
    <%= will_paginate %>
</div>

nozama/app/views/sales/index.html.erb
<% provide(:title, 'Sales') %>
<h1>Sales</h1>
<div class='text-center'>
    <%= will_paginate %>
</div>
<table align="center" class="center hero-unit">
  <thead>
  <tr>
    <th>FNSKU</th>
    <td>&nbsp&nbsp</td>
    <th>Shipment Date</th>
    <td>&nbsp&nbsp</td>

    <th>Days in Inventory</th>
    <td>&nbsp&nbsp</td>
    <th>Price</th>
    <td>&nbsp&nbsp</td>
    <th>Amazon Order ID</th>
    <td>&nbsp&nbsp</td>
    <th>Delete</th>
  </tr>
  </thead>

  <tbody>
  <% @sales.each do |sale| %>
      <tr>
        <td><%= link_to sale.fnsku, sale %></td>
        <td>&nbsp&nbsp</td>
        <td><%= sale.shipment_date.strftime('%m/%d/%Y') %></td>
        <td>&nbsp&nbsp</td>
        <td><%= sale.days_in_inventory.abs %></td>
        <td>&nbsp&nbsp</td>
        <td><%= number_to_currency(sale.item_price_per_unit) %></td>
        <td>&nbsp&nbsp</td>
        <td><%= link_to sale.amazon_order_id, sale %></td>
        <td>&nbsp&nbsp</td>
        <td><%= link_to 'Delete', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<div class='text-center'>
    <%= will_paginate %>
</div>

nozama/app/views/sales/new.html.erb
<% provide(:title, 'Upload Sales Data') %>
<h1>Upload Sales Data</h1>

<div class="row">
    <div class="span6 offset3" align="center">
        <%= form_for(@sale) do |f| %>
            <%= f.label :upload, 'Upload Sales File' %>
            <%= f.file_field :file %>
            <br/>
            <%= submit_tag 'Upload File', class: 'btn btn-small btn-primary', disable_with: 'Uploading...', :name => 'name' %>
        <% end %>
    </div>
</div>

<%= link_to 'Back', sales_path %>

nozama/app/views/sales/search.html.erb
<% provide(:title, 'Search Sales Data') %>
<h1>Search Inventory Data</h1>

<div class="row">
    <div class="span6 offset3">
        <%= form_for(@sale) do |f| %>
            <%= f.label :amazon_order_id, 'Amazon Order ID' %>
            <%= f.text_field :amazon_order_id %>
            <br/>
            <%= f.label :fnsku, 'FNSKU' %>
            <%= f.text_field :fnsku %>
            <br/>
            <%= submit_tag 'Search', class: 'btn btn-small btn-primary', disable_with: 'Searching...', :name => 'name' %>
        <% end %>
    </div>
</div>

<%= link_to 'Back', sales_path %>

nozama/app/views/sales/search_index.html.erb
<% provide(:title, 'Sales') %>
<h1>Sales</h1>
<div class='text-center'>
    <%= will_paginate %>
</div>
<table align="center">
    <thead>
    <tr>
        <th>Amazon Order ID</th>
        <td>&nbsp&nbsp</td>
        <th>FNSKU</th>
        <td>&nbsp&nbsp</td>
        <th>Shipment Date</th>
        <td>&nbsp&nbsp</td>
        <th>Delete</th>
    </tr>
    </thead>

    <tbody>
    <% @sales.each do |sale| %>
        <tr>
            <td><%= link_to sale.amazon_order_id, sale %></td>
            <td>&nbsp&nbsp</td>
            <td><%= sale.fnsku %></td>
            <td>&nbsp&nbsp</td>
            <td><%= sale.shipment_date.strftime('%m/%d/%Y') %></td>
            <td>&nbsp&nbsp</td>
            <td><%= link_to 'Delete', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
</table>
<div class='text-center'>
    <%= will_paginate %>
</div>

nozama/app/views/sales/show.html.erb
<% provide(:title, @sale.amazon_order_id) %>

<p id="notice"><%= notice %></p>

<p>
    <strong>Amazon Order ID:</strong>
    <%= @sale.amazon_order_id %>
    <br/>
    <strong>Days In Inventory:</strong>
    <%= @sale.days_in_inventory.abs %>
    <br/>
    <strong>Shipment Date:</strong>
    <%= @sale.shipment_date.strftime('%m/%d/%Y') %>
    <br/>
    <strong>SKU:</strong>
    <%= @sale.sku %>
    <br/>
    <strong>FNSKU:</strong>
    <%= @sale.fnsku %>
    <br/>
    <strong>ASIN:</strong>
    <%= @sale.asin %>
    <br/>
    <strong>Fulfillment Center ID:</strong>
    <%= @sale.fulfillment_center_id %>
    <br/>
    <strong>Quantity Sold:</strong>
    <%= @sale.quantity %>
    <br/>
    <strong>Currency:</strong>
    <%= @sale.currency %>
    <br/>
    <strong>Item Price Per Unit:</strong>
    <%= number_to_currency(@sale.item_price_per_unit) %>
    <br/>
    <strong>Shipping Price:</strong>
    <%= number_to_currency(@sale.shipping_price) %>
    <br/>
    <strong>Gift Wrap Price:</strong>
    <%= number_to_currency(@sale.gift_wrap_price) %>
    <br/>
    <strong>Ship City:</strong>
    <%= @sale.ship_city %>
    <br/>
    <strong>Ship State:</strong>
    <%= @sale.ship_state %>
    <br/>
    <strong>Ship Postal Code:</strong>
    <%= @sale.ship_postal_code %>
    <br/>
</p>

nozama/app/views/sales/statistics.html.erb
<% provide(:title, 'Statistics') %>
<%= javascript_include_tag 'jquery-2.0.3', 'highcharts' %>
<h1>Statistics</h1>

<script type='text/javascript' charset='utf-8'>
   $(function() {
      new Highcharts.Chart({
          chart: {
              renderTo: 'revenue_chart'
          },
          title: {
              text: 'Revenue Over the Past 30 Days'
          },
          xAxis: {
              type: 'datetime'
          },
          yAxis: {
              title: {
                  text: 'Dollars'
              },
              min: 0
          },
          tooltip: {
              formatter: function() {
                  return Highcharts.dateFormat('%B %e, %Y', this.x) + ': ' +
                          '$' + Highcharts.numberFormat(this.y, 2);
              }
          },
          series: [{
              name: 'Revenue',
              pointInterval: <%= 1.day * 1000 %>,
              pointStart: <%= 1.month.ago.to_i * 1000 %>,
              data: <%= (1.months.ago.to_date..Date.today).map { |date| Sale.total_for(date).to_f }.inspect %>
          }]
      });
   });

   $(function() {
       new Highcharts.Chart({
           chart: {
               type: 'column',
               renderTo: 'sales_chart'
           },
           title: {
               text: 'Sales Over the Past 30 Days'
           },
           xAxis: {
               type: 'datetime'
           },
           yAxis: {
               title: {
                   text: '# Sales'
               },
               min: 0
           },
           tooltip: {
               formatter: function() {
                   return Highcharts.dateFormat('%B %e, %Y', this.x) + ': ' + this.y;
               }
           },
           series: [{
               name: 'Sales',
               pointInterval: <%= 1.day * 1000 %>,
               pointStart: <%= 1.month.ago.to_i * 1000 %>,
               data: <%= (1.months.ago.to_date..Date.today).map { |date| Sale.totalcount_for(date).to_f }.inspect %>
           }]
       });
   });
</script>

<div id='revenue_chart' style='width:560px; height:300px; margin-left:auto; margin-right:auto'></div>
<br/><br/>
<div id='sales_chart' style='width:560px; height:300px; margin-left:auto; margin-right:auto'></div>