nozama/config/routes.rb
Nozama::Application.routes.draw do

  match '/indexbatchinventory', to: 'inventories#batch_index', via: 'get'
  match '/batchinventory', to: 'inventories#batch_inventory', via: 'get'
  match '/batchinventorydeleteone', to: 'inventories#batch_delete', via: 'get'
  match '/batchinventorydeleteall', to: 'inventories#batch_delete_all', via: 'get'
  match '/batchinventoryshow', to: 'inventories#show', via: 'get'
  match '/inventorysearch', to: 'inventories#search', via: 'get'
  match '/inventorysearchindex', to: 'inventories#search_index', via: 'get'

  match '/indexbatchsales', to: 'sales#batch_index', via: 'get'
  match '/batchsales', to: 'sales#batch_sales', via: 'get'
  match '/batchsalesdeleteone', to: 'sales#batch_delete', via: 'get'
  match '/batchsalesdeleteall', to: 'sales#batch_delete_all', via: 'get'
  match '/salessearch', to: 'sales#search', via: 'get'
  match '/salessearchindex', to: 'sales#search_index', via: 'get'
  match '/salesstatistics', to: 'sales#statistics', via: 'get'

  resources :users
  resources :inventories
  resources :sales
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'

end

nozama/app/models/inventory.rb
class Inventory < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
end

nozama/app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :signed_in_user, only: [:index, :create, :edit, :update, :destroy]
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]

  # GET /inventories
  # GET /inventories.json
  def index
    @inventories = current_user.inventories.where(:user_id => current_user.id).where('quantity_remaining > 0').group(:fnsku, :received_date).paginate(page: params[:page])
  end

  def batch_inventory
    @inventories = Inventory.where(:user_id => current_user.id, :batch_id => params[:batch_id]).group(:fnsku, :received_date).paginate(page: params[:page])
  end

  def batch_index
    @inventories = Inventory.where(:user_id => current_user.id).group(:batch_id).paginate(page: params[:page])
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
    fnsku = @inventory.fnsku
    received = @inventory.received_date

    if params[:batch_id]
    else
      @inventory.quantity = current_user.inventories.where(:user_id => current_user.id, :fnsku => fnsku, :received_date => received).sum(:quantity)
      @inventory.quantity_remaining = current_user.inventories.where(:user_id => current_user.id, :fnsku => fnsku, :received_date => received).sum(:quantity_remaining)
    end
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  def search
    @inventory = Inventory.new
  end

  def search_index
    if params[:product_name] && params[:id].nil?
      @inventories = current_user.inventories.where(:user_id => current_user.id).where('product_name LIKE ?', '%' + params[:product_name] + '%').group(:fnsku, :received_date).paginate(page: params[:page])
    elsif params[:product_name]
      @inventories = current_user.inventories.where(:user_id => current_user.id).where('quantity_remaining > 0').where('product_name LIKE ?', '%' + params[:product_name] + '%').group(:fnsku, :received_date).paginate(page: params[:page])
    elsif params[:fnsku] && params[:id].nil?
      @inventories = current_user.inventories.where(:user_id => current_user.id).where(:fnsku => params[:fnsku]).group(:fnsku, :received_date).paginate(page: params[:page])
    elsif params[:fnsku]
      @inventories = current_user.inventories.where(:user_id => current_user.id).where('quantity_remaining > 0').where(:fnsku => params[:fnsku]).group(:fnsku, :received_date).paginate(page: params[:page])
    end
  end

  # POST /inventories
  # POST /inventories.json
  def create
    if params[:name] == 'Upload File'
      fileUpload = true
    elsif params[:name] == 'Search'
      searchQuery = true
    end

    if params[:inventory] && params[:inventory][:file]
      inventory = Inventory.where(:user_id => current_user.id).last

      if inventory.nil?
        batchID = 1
      else
        batchID = inventory.batch_id + 1
      end

      lines = params[:inventory][:file].tempfile.readlines.map(&:chomp)
      validHeader = lines[0].split(/\t/)

      if validHeader[0] == 'received-date'
        lines.shift
        begin
          Inventory.transaction do
              lines.each do |line|
                parse = line.split(/\t/)
                @inventory = current_user.inventories.build(batch_id: batchID, received_date: parse[0], fnsku: parse[1], sku: parse[2], product_name: parse[3].gsub(/[^\u0000-\u007F]/, ''), quantity: parse[4], fba_shipment_id: parse[5],
                                                 fulfillment_center_id: parse[6], quantity_remaining: parse[4])
                @inventory.save!
              end
          end
        rescue ActiveRecord::StatementInvalid
          notice = 'Inventory upload was unsuccessful.'
          redirect_to new_inventory_path, :notice => notice
          return
        end
      else
        @inventory = Inventory.new
      end
    elsif params[:inventory] && (params[:inventory][:product_name] != '')
      if params[:inventory][:id].nil?
        redirect_to inventorysearchindex_path(:product_name => params[:inventory][:product_name])
      else
        redirect_to inventorysearchindex_path(:product_name => params[:inventory][:product_name], :id => params[:inventory][:id])
      end
    elsif params[:inventory] && (params[:inventory][:fnsku] != '')
      if params[:inventory][:id].nil?
        redirect_to inventorysearchindex_path(:fnsku => params[:inventory][:fnsku])
      else
        redirect_to inventorysearchindex_path(:fnsku => params[:inventory][:fnsku], :id => params[:inventory][:id])
      end
    else
      @inventory = Inventory.new
    end

    if fileUpload
      respond_to do |format|
        if @inventory.save
          format.html { redirect_to inventories_path, notice: 'Inventory was successfully uploaded.' }
          format.json { render action: 'show', status: :created, location: @inventory }
        else
          format.html { redirect_to new_inventory_path, notice: 'Inventory upload was unsuccessful.' }
          format.json { render json: @inventory.errors, status: :unprocessable_entity }
        end
      end
    elsif searchQuery
      if params[:inventory][:product_name] == '' && params[:inventory][:fnsku] == ''
        respond_to do |format|
          format.html { redirect_to inventorysearch_path, notice: 'Enter product name or FNSKU to search.' }
          format.json { render json: @inventory.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to @inventory, notice: 'Inventory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Item was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def batch_delete
    Inventory.delete(params[:id])
    respond_to do |format|
      format.html { redirect_to batchinventory_path(:batch_id => params[:batch_id]), notice: 'Item was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def batch_delete_all
    Inventory.where(:batch_id => params[:batch_id], :user_id => current_user.id).delete_all
    respond_to do |format|
      format.html { redirect_to indexbatchinventory_path, notice: 'Batch was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_params
      params.require(:inventory).permit(:user_id, :received_date, :fnsku, :sku, :product_name,:quantity, :fba_shipment_id, :fulfillment_center_id)
    end
end

nozama/app/helpers/inventories_helper.rb
module InventoriesHelper
end

nozama/app/views/inventories/_form.html.erb
<%= form_for(@inventory) do |f| %>
  <% if @inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventory.errors.count, 'error') %> prohibited this inventory from being saved:</h2>

      <ul>
      <% @inventory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

nozama/app/views/inventories/batch_index.html.erb
<% provide(:title, 'Batch Inventory Index') %>
<h1>Batch Inventory Index</h1>
<div class='text-center'>
    <%= will_paginate %>
</div>
<table align="center">
    <thead>
    <tr>
        <th>Batch ID</th>
        <td>&nbsp&nbsp</td>
        <th>Uploaded</th>
        <td>&nbsp&nbsp</td>
        <th>Delete</th>
    </tr>
    </thead>

    <tbody>
    <% @inventories.each do |inventory| %>
        <tr>
            <td><%= link_to inventory.batch_id, batchinventory_path(:batch_id => inventory.batch_id) %></td>
            <td>&nbsp&nbsp</td>
            <td><%= inventory.created_at.strftime('%m/%d/%Y') %></td>
            <td>&nbsp&nbsp</td>
            <td><%= link_to 'Delete', batchinventorydeleteall_path(:batch_id => inventory.batch_id), data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
</table>
<div class='text-center'>
    <%= will_paginate %>
</div>

nozama/app/views/inventories/batch_inventory.html.erb
<% provide(:title, 'Batch Inventory') %>
<h1>Batch Inventory</h1>
<div class='text-center'>
    <%= will_paginate %>
</div>
<table align="center">
    <thead>
    <tr>
        <th>Product Name</th>
        <td>&nbsp&nbsp</td>
        <th>Recieved Date</th>
        <td>&nbsp&nbsp</td>
        <th>Delete</th>
    </tr>
    </thead>

    <tbody>
    <% @inventories.each do |inventory| %>
        <tr>
            <td><%= link_to inventory.product_name, batchinventoryshow_path(:id => inventory.id, :batch_id => inventory.batch_id) %></td>
            <td>&nbsp&nbsp</td>
            <td><%= inventory.received_date.strftime('%m/%d/%Y') %></td>
            <td>&nbsp&nbsp</td>
            <td><%= link_to 'Delete', batchinventorydeleteone_path(:id => inventory.id, :batch_id => inventory.batch_id), data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
</table>
<div class='text-center'>
    <%= will_paginate %>
</div>

nozama/app/views/inventories/index.html.erb
<% provide(:title, 'Inventory') %>
<h1>Inventory</h1>
<div class = 'text-center'>
    <%= will_paginate %>
</div>
<table align="center" class="center hero-unit">
  <thead>
  <tr>
    <th>FNSKU</th>
    <td>&nbsp&nbsp</td>
    <th>Received Date</th>
    <td>&nbsp&nbsp</td>
    <th>Days In Inventory</th>
    <td>&nbsp&nbsp</td>
    <th>Received</th>
    <td>&nbsp&nbsp</td>
    <th>Remaining</th>
    <td>&nbsp&nbsp</td>
    <th>Product Name</th>
    <td>&nbsp&nbsp</td>

    <th>Delete</th>
  </tr>
  </thead>

  <tbody>
  <% @inventories.each do |inventory| %>
      <tr>
        <td><%= link_to inventory.fnsku, inventory %></td>
        <td>&nbsp&nbsp</td>
        <td><%= inventory.received_date.strftime('%m/%d/%Y') %></td>
        <td>&nbsp&nbsp</td>
        <td><%= (Date.today - inventory.received_date).to_i %></td>
        <td>&nbsp&nbsp</td>
        <td><%= inventory.quantity %></td>
        <td>&nbsp&nbsp</td>
        <td><%= inventory.quantity_remaining %></td>
        <td>&nbsp&nbsp</td>
        <td><%= link_to inventory.product_name, inventory %></td>
        <td>&nbsp&nbsp</td>
        <td><%= link_to 'Delete', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<div class='text-center'>
    <%= will_paginate %>
</div>

nozama/app/views/inventories/new.html.erb
<% provide(:title, 'Upload Inventory Data') %>
<h1>Upload Inventory Data</h1>

<div class="row">
    <div class="span6 offset3" align="center">
        <%= form_for(@inventory) do |f| %>
            <%= f.label :upload, 'Upload Inventory File' %>
            <%= f.file_field :file %>
            <br/>
            <%= submit_tag 'Upload File', class: 'btn btn-small btn-primary', disable_with: 'Uploading...', :name => 'name' %>
        <% end %>
    </div>
</div>

<%= link_to 'Back', inventories_path %>

nozama/app/views/inventories/search.html.erb
<% provide(:title, 'Search Inventory Data') %>
<h1>Search Inventory Data</h1>

<div class="row">
    <div class="span6 offset3">
        <%= form_for(@inventory) do |f| %>
            <%= f.label :product_name, 'Product Name' %>
            <%= f.text_field :product_name %>
            <br/>
            <%= f.label :fnsku, 'FNSKU' %>
            <%= f.text_field :fnsku %>
            <br/>
            <%= f.check_box :id, {}, true, false %>
            <%= f.label :active, 'Search Active Inventory Only', class: 'checkbox inline' %>
            <br/><br/>
            <%= submit_tag 'Search', class: 'btn btn-small btn-primary', disable_with: 'Searching...', :name => 'name' %>
        <% end %>
    </div>
</div>

<%= link_to 'Back', inventories_path %>

nozama/app/views/inventories/search_index.html.erb
<% provide(:title, 'Inventory') %>
<h1>Inventory</h1>
<div class='text-center'>
    <%= will_paginate %>
</div>
<table align="center">
    <thead>
    <tr>
        <th>Product Name</th>
        <td>&nbsp&nbsp</td>
        <th>Days In Inventory</th>
        <td>&nbsp&nbsp</td>
        <th>Delete</th>
    </tr>
    </thead>

    <tbody>
    <% @inventories.each do |inventory| %>
        <tr>
            <td><%= link_to inventory.product_name, inventory %></td>
            <td>&nbsp&nbsp</td>
            <td><%= (Date.today - inventory.received_date).to_i %></td>
            <td>&nbsp&nbsp</td>
            <td><%= link_to 'Delete', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
</table>
<div class='text-center'>
    <%= will_paginate %>
</div>

nozama/app/views/inventories/show.html.erb
<% provide(:title, @inventory.product_name) %>

<p id="notice"><%= notice %></p>

<p>
    <strong>Product Name:</strong>
    <%= @inventory.product_name %>
    <br/>
    <strong>Days In Inventory:</strong>
    <%= (Date.today - @inventory.received_date).to_i %>
    <br/>
    <strong>Received Date:</strong>
    <%= @inventory.received_date %>
    <br/>
    <strong>SKU:</strong>
    <%= @inventory.sku %>
    <br/>
    <strong>FNSKU:</strong>
    <%= @inventory.fnsku %>
    <br/>
    <strong>FBA Shipment ID:</strong>
    <%= @inventory.fba_shipment_id %>
    <br/>
    <strong>Quantity Shipped:</strong>
    <%= @inventory.quantity %>
    <br/>
    <strong>Quantity Remaining:</strong>
    <%= @inventory.quantity_remaining %>
    <br/>
    <strong>Fulfillment Center ID:</strong>
    <%= @inventory.fulfillment_center_id %>
    <br/>

    <br/>
    <strong><%= link_to 'Click For Associated Sales', sales_path(:fnsku => @inventory.fnsku, :item_id => @inventory.id) %></strong>
</p>